name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This step would be for building your Docker image, like in the lab.
      # You can uncomment and modify this based on your Dockerfile and needs.
      # - name: Build Docker image
      #   run: docker build -t discounts-service .
      #
      # - name: Deploy to Staging
      #   run: echo "Deploying to staging environment..."
      
      - name: Run Datadog Synthetic test
        uses: DataDog/synthetics-ci-github-action@v2
        with:
          # Use GitHub Secrets to store your Datadog keys securely
          api_key: '9216667f1ebc992fa6365e06b0417998'
          app_key: 'a0f906a5bf21eecc58098cca5f7e5803eae5903c'
          public_ids: 'nqf-mix-ndf'
          
          # Optional: Specify your Datadog site (e.g., datadoghq.eu, us3.datadoghq.com)
          datadog_site: 'app.datadoghq.com'
