name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This step would be for building your Docker image, like in the lab.
      # You can uncomment and modify this based on your Dockerfile and needs.
      # - name: Build Docker image
      #   run: docker build -t discounts-service .
      #
      # - name: Deploy to Staging
      #   run: echo "Deploying to staging environment..."
      
      - name: Run Datadog Synthetic test
        uses: DataDog/synthetics-ci-github-action@v2
        with:
          # Use GitHub Secrets to store your Datadog keys securely
          api_key: ${{ secrets.DATADOG_API_KEY }}
          app_key: ${{ secrets.DATADOG_APP_KEY }}
          
          # Use the public ID of the specific test you want to run.
          # You can define this as a repository secret or just hardcode it here
          # since it is not sensitive.
          public_ids: 'nqf-mix-ndf'
          
          # Optional: Specify your Datadog site (e.g., datadoghq.eu, us3.datadoghq.com)
          # datadog_site: 'us5.datadoghq.com'
