name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t discounts-service .

      - name: Deploy to Staging
        # In a real-world scenario, this would be a step to deploy to a staging server.
        # For a local test, you can just print a message.
        run: echo "Deploying to staging environment..."

      - name: Run Synthetic Test on Staging
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g @datadog/datadog-ci
      - run: datadog-ci synthetics run-tests
        env:
          DATADOG_API_KEY: 9216667f1ebc992fa6365e06b0417998
          DATADOG_APP_KEY: a0f906a5bf21eecc58098cca5f7e5803eae5903c
          DATADOG_PUBLIC_ID: nqf-mix-ndf
          # You would also need to specify the staging environment URL
          # DATADOG_SITE: "us5.datadoghq.com" # or your specific Datadog site

      - name: Deploy to Production
        # This step would run only if the previous synthetic test passes.
        # This is a key feature of CI/CD and is handled automatically by GitHub Actions.
        run: echo "Synthetic test passed. Deploying to production..."
